### ISSUE TITLE
smoke test fails

### ISSUE THREAD

**Issue by rofe** [adobe/helix-continuous#17]
**Description**
The smoke test fails in CircleCI with the following output:
```
  1) project-helix.io renders properly
       Root ("/" / index.html) is rendered using project htl scripts:

      AssertionError [ERR_ASSERTION]: nav in index (summary_html.htl) is included via ESI include
      + expected - actual

      -false
      +true
      
      at Context.it (test/smoke/test.hlx.up.js:51:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  2) project-helix.io renders properly
       README.html page is rendered using project htl scripts:

      AssertionError [ERR_ASSERTION]: nav in README (summary_html.htl) is included via ESI include
      + expected - actual

      -false
      +true
      
      at Context.it (test/smoke/test.hlx.up.js:59:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  3) project-helix.io renders properly
       content assets in index.html check:

      AssertionError [ERR_ASSERTION]: no assets found
      + expected - actual

      -false
      +true
      
      at Context.it (test/smoke/test.hlx.up.js:82:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```
Seems like there is some problem with ESI includes? For what it's worth, the related commit is https://github.com/adobe/helix-cli/commit/6ba5a88a4d55c91d0f888cbc2bc9a6697d615bd7

**To Reproduce**
See here for first failure (all subsequent runs are failing with the same output):
https://circleci.com/gh/adobe/helix-cli/8016

**Expected behavior**
The smoke test succeeds.

**Comment by tripodsan** [comment]
last run that was still successful:
https://circleci.com/gh/adobe/helix-continuous/2782

```
+ @adobe/fastly-native-promises@0.0.0-semantically-released
+ @adobe/git-server@0.9.17-pre.4
+ @adobe/helix-shared@1.3.2
+ @adobe/helix-simulator@2.12.9
+ @adobe/helix-testutils@0.2.0
+ @adobe/htlengine@2.2.2
+ @adobe/openwhisk-loggly-wrapper@0.4.3-pre.2
+ @adobe/parcel-plugin-htl@2.1.9
```

first run that failed:
https://circleci.com/gh/adobe/helix-continuous/2783

```
+ @adobe/fastly-native-promises@0.0.0-semantically-released
+ @adobe/git-server@0.9.17-pre.4
+ @adobe/helix-pipeline@2.0.0
+ @adobe/helix-shared@1.3.2
+ @adobe/helix-simulator@2.12.9
+ @adobe/helix-testutils@0.2.0
+ @adobe/htlengine@2.3.0
+ @adobe/openwhisk-loggly-wrapper@0.4.3-pre.2
+ @adobe/parcel-plugin-htl@2.1.9
```

**Comment by tripodsan** [comment]
this is a regression of: 

https://github.com/adobe/htlengine/issues/53

**Comment by tripodsan** [comment]
fixed.
